### ISSUE TITLE
Build iOS targets with Xcode 12.5

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#173]
### Issue type

Feature request

### Description of the problem

The iOS project can't build with Xcode 12.5 beta 1 and beta 2.

`[SRGPage new]` and `[SRGRequest new]` are unavailable.

### Environment information

* Application version: Xcode 12.5
* iOS / tvOS version: iOS build
* Device: Any

### Reproducibility

Always reproducible

**Comment by pyby** [comment]
From https://github.com/SRGSSR/srgnetwork-apple/issues/11 proposition, a test in available on `feature/xcode-12.5`.

**Comment by pyby** [comment]
After discussed with @defagos , we released a [SRGNetwork 3.0.2](https://github.com/SRGSSR/srgnetwork-apple/releases/tag/3.0.2) patch version that fixes Xcode 12.5 compilation errors in Play project.
